---
- name: app servers
  hosts: client-apps
  become: yes
  vars: 
    jenkinspath: /var/lib/jenkins/workspace
    apppath: /var/www
    appname: TwoTierApp_FlaskPy

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install needed packages for Flask
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv

    - name: Clone the Flask app repository
      git:
        repo: 'https://github.com/chanelskil/TwoTier-Flask-App-Deployment.git'
        dest: "{{ apppath }}/{{ appname }}"
        version: master

    - name: Create a Python virtual environment
      shell: python3 -m venv "{{ apppath }}/{{ appname }}/venv"
      args:
        creates: "{{ apppath }}/{{ appname }}/venv/bin/activate"

    - name: Install Python dependencies
      pip:
        requirements: "{{ apppath }}/{{ appname }}/requirements.txt"
        virtualenv: "{{ apppath }}/{{ appname }}/venv"

    - name: Verify the installation of dependencies
      shell: |
        . "{{ apppath }}/{{ appname }}/venv/bin/activate"
        pip check
      register: pip_check_output

    - name: Display pip check result
      debug:
        msg: "{{ pip_check_output.stdout }}"

    - name: Start the Flask app
      shell: |
        . "{{ apppath }}/{{ appname }}/venv/bin/activate"
        python "{{ apppath }}/{{ appname }}/app.py"
      args:
        chdir: "{{ apppath }}/{{ appname }}"
